FROM python:3
RUN pip install mysql-connector-python
ADD getdata.py  /
ADD flask_wrapper_load.py /
RUN pip install pystrich
RUN pip install mysqlclient
RUN pip install flask
RUN pip install pandas
CMD [ "python", "./flask_wrapper_load.py" ]